# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
     # For instance in our GitHub action:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn

      # 👇 Run Chromatic as normal for your Storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      # 👇 Run your E2E tests *before* running Chromatic for your E2E test archives
      - name: E2E tests
        run: yarn playwright test

      # 👇 Run Chromatic for your E2E test archives
      - name: Publish E2E Archives to Chromatic
        uses: chromaui/action@v1
        with:
          # 👇 This is the token for the archive project
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # 👇 Tell Chromatic to build the Archive Storybook
          buildScriptName: build-archive-storybook
